### ISSUE TITLE
Maureen needs an option to create the ArgoCD application that will clean up its resources

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/ibm-garage-cloud-cli#355]
A finalizer on the ArgoCD application is required to perform a cascading delete using kubectl. By default the finalizer is not added so when the ArgoCD application is deleted the resources remain.

Initially, an option should be provided to allow the finalizer to be added which is defaulted to false. If things work out as expected the finalizer should be added by default.

```yaml
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
```

https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/
